development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: seanyao

# adapter: sqlite3
# database: db/development.sqlite3
# pool: 5
# timeout: 5000

test: &test
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: seanyao

# adapter: sqlite3
# database: db/test.sqlite3
# pool: 5
# timeout: 5000

#production:
#  adapter: postgresql
#  encoding: unicode
#  database: sample_app_production
#  pool: 5
#  username: s2one
#  password:

# adapter: sqlite3
# database: db/production.sqlite3
# pool: 5
# timeout: 5000

cucumber:
  <<: *test